### ISSUE TITLE
Not able to install lucem_illud_2020

### ISSUE THREAD

**Issue by iarakshana** [Computational-Content-Analysis-2020/frequently-asked-questions-spring#6]
Hi,
I am not able to download the lucem program. I keep getting an error with torch and traits. I tried downloading them separately through pip install torch but still kept getting the same error.  The error said Microsoft Visual C++ 14.0 is required, which I installed however I'm still getting these errors in red. Any help would be great! Thanks!

**Comment by bhargavvader** [comment]
Hmmm, that's annoying. We don't need those packages right away (they come up in Week 7/8) so I've updated the package to not have them immediately. 

We will need them at some point though... could you post a screenshot so I can debug better?  Also sometimes just restarting your machine will solve the issue.

**Comment by bhargavvader** [comment]
You can try installing ```lucem_illud_2020``` again - it should work!

**Comment by iarakshana** [comment]
![image](https://user-images.githubusercontent.com/32250503/78722246-af7d5e80-78ee-11ea-833d-06d59fa4e850.png)

![image](https://user-images.githubusercontent.com/32250503/78722290-c6bc4c00-78ee-11ea-89eb-4e449068296c.png)

These are the screenshots from when I was trying to install it. I get the same error when I tried to reinstall. I restarted my computer but it didn't seem to resolve the issue.

But, I think for the first homework, I think I can do it without the lucem package? Thank you!

**Comment by nwrim** [comment]
I had the same error message but it worked when I uninstalled and reinstalled visual C++ and ran `pip install traits` separately. 

Still could not get it installed on a conda environemnt I made for the course, but somehow it worked on the base environment. Also after installing on base, I was able to install it on the conda environment too - which makes me very confused.

**Comment by iarakshana** [comment]
Will try this and see, thanks!

**Comment by Yilun0221** [comment]
you can use:
pip install git+https://github.com/Computational-Content-Analysis-2020/lucem_illud_2020.git
in the prompt!

**Comment by pdiazm** [comment]
Hello Bhargav,

I get the same error as Nak and Immanuelle - and have tried their proposed solution of uninstalling and reinstalling Visual C++ - but it doesn't seem to be working for me. I'm only installing the basic MSBuild Tools. Should I be installing other components?

Below is a screenshot of the error I'm getting:
![image](https://user-images.githubusercontent.com/47371280/79010436-91e70980-7b27-11ea-9dc4-78bfda5e98b5.png)

Please let me know what is the best way to proceed.

Thank you,
Paulino

**Comment by iarakshana** [comment]
I did a bunch of stuff and it seems to have installed now. Not sure which one of them worked.

`pip install --upgrade setuptools`

`set SLUGIFY_USES_TEXT_UNIDECODE=yes`

I uninstalled Visual C++2019 and reinstalled an older version and it's now working for me. In the part where they ask which packages I also clicked Windows 10. I had uninstalled and reinstalled 2019 previously and that hadn't worked for me.

Hope this helps!

https://stackoverflow.com/questions/52203441/error-while-install-airflow-by-default-one-of-airflows-dependencies-installs-a

https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat

**Comment by pdiazm** [comment]
Thank you so much Adriana! I'll try these things and let you know how it goes.
